[tox]
minversion = 4.0
envlist = py312,pep8
skipsdist = False

[testenv]
usedevelop = True
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
commands =
    stestr run {posargs}
setenv =
    PYTHONDONTWRITEBYTECODE = 1

[testenv:pep8]
deps =
    ruff
commands =
    ruff check txt2png.py tests/

[testenv:venv]
commands = {posargs}
